<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.inventory/xml/schema/CRM/Inventory/InventoryProduct.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:0671f926f9e0254f82d61561ad280487)
 */
use CRM_Inventory_ExtensionUtil as E;

/**
 * Database access object for the InventoryProduct entity.
 */
class CRM_Inventory_DAO_InventoryProduct extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_inventory_product';

  /**
   * Field to show when displaying a record.
   *
   * @var string
   */
  public static $_labelField = 'label';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique InventoryProduct ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $label;

  /**
   * Product Code SKU.
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_code;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $external_code;

  /**
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_description;

  /**
   * What the member pays for replacement.
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $listed_price;

  /**
   * Fair market value for device.
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $current_price;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_brand;

  /**
   * Displayed to the user as a place to document additional features or issues.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_note;

  /**
   * FK to Category
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_category_id;

  /**
   * Full absolute URL
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $image_url;

  /**
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $help_url;

  /**
   * Packed Weight
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $packed_weight;

  /**
   * Packed Height
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $packed_height;

  /**
   * Packed Width
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $packed_width;

  /**
   * Packed Depth
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $packed_depth;

  /**
   * Battery backup time.
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_variant_battery;

  /**
   * Device Speed.
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_variant_speed;

  /**
   * Supports external antenna
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $antenna;

  /**
   * Supports tethering via USB or Ethernet
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $tether;

  /**
   * Supports charging external devices
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $powerbank;

  /**
   * Can run without a battery
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $batteryless;

  /**
   * Supports 4G networks
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $network_4g;

  /**
   * Supports 5G networks
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $network_5g;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $has_sim;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $has_device;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $warranty_type_id;

  /**
   * Feet, pounds, and gallons are all examples of units of measure.
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $uom;

  /**
   * Screen size details. e.g. 5.81", OLED 2340x1080
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $screen;

  /**
   * Storage size. e.g. 128 GB
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $storage;

  /**
   * Product Memory size. e.g. 4 GB
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $memory;

  /**
   * e.g. Black
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $color;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $premium_is_optional;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $premium_needs_address;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $premium_shirt_count;

  /**
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $premium_device_count;

  /**
   * FK to Warehouse
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $warehouse_id;

  /**
   * The quantity on hand.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $quantity_available;

  /**
   * The minimum number of units required to ensure no shortages occur at this warehouse.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $minimum_quantity_stock_level;

  /**
   * The maximum number of units desired in stock, i.e. to avoid overstocking.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $maximum_quantity_stock_level;

  /**
   * The minimum number of units required to ensure no shortages occur at this warehouse.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $reorder_point;

  /**
   * Use to locate the item in warehouse
   *
   * @var string
   *   (SQL type: varchar(256))
   *   Note that values will be retrieved from the database as a string.
   */
  public $row;

  /**
   * Use to locate the item in warehouse
   *
   * @var string
   *   (SQL type: varchar(256))
   *   Note that values will be retrieved from the database as a string.
   */
  public $shelf;

  /**
   * Controls display sort order.
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $weight;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_serialize;

  /**
   * When a model is discontinued, a membership cannot be renewed until they upgrade the device.
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_discontinued;

  /**
   * If not active, new devices of this type will not be available. Users with existing devices of this type will still see their devices listed.
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Show or hide this model on the admin dashboard.
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $inventory_display;

  /**
   * If defined, this note will replace the default inventory message that is based on the inventory status.
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $inventory_status_note;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $inventory_status;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_inventory_product';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Inventory Products') : E::ts('Inventory Product');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'inventory_product_id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique InventoryProduct ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.id',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'inventory_product_label' => [
          'name' => 'label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Label'),
          'required' => TRUE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.label',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_code' => [
          'name' => 'product_code',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Code'),
          'description' => E::ts('Product Code SKU.'),
          'required' => TRUE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_code',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_external_code' => [
          'name' => 'external_code',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('External Code'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.external_code',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_description' => [
          'name' => 'product_description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Product Description'),
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_description',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'inventory_product_listed_price' => [
          'name' => 'listed_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Listed Price'),
          'description' => E::ts('What the member pays for replacement.'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.listed_price',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Listed Price"),
          ],
          'add' => NULL,
        ],
        'inventory_product_current_price' => [
          'name' => 'current_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Current Price'),
          'description' => E::ts('Fair market value for device.'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.current_price',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Current Price"),
          ],
          'add' => NULL,
        ],
        'inventory_product_brand' => [
          'name' => 'product_brand',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Brand'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_brand',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Product Brand"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'product_brand',
            'optionEditPath' => 'civicrm/admin/options/product_brand',
          ],
          'add' => '5.63',
        ],
        'inventory_product_note' => [
          'name' => 'product_note',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Product Note'),
          'description' => E::ts('Displayed to the user as a place to document additional features or issues.'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_note',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'inventory_product_category_id' => [
          'name' => 'product_category_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Product Category'),
          'description' => E::ts('FK to Category'),
          'required' => TRUE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_category_id',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventoryCategory',
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Product Category"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_inventory_category',
            'keyColumn' => 'id',
            'labelColumn' => 'title',
          ],
          'add' => NULL,
        ],
        'inventory_product_image_url' => [
          'name' => 'image_url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Image URL'),
          'description' => E::ts('Full absolute URL'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.image_url',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_help_url' => [
          'name' => 'help_url',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Help URL'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.help_url',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_variant_weight' => [
          'name' => 'packed_weight',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Packed Weight'),
          'description' => E::ts('Packed Weight'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.packed_weight',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Packed Weight"),
          ],
          'add' => NULL,
        ],
        'inventory_product_variant_height' => [
          'name' => 'packed_height',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Packed Height'),
          'description' => E::ts('Packed Height'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.packed_height',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Packed Height"),
          ],
          'add' => NULL,
        ],
        'inventory_product_variant_width' => [
          'name' => 'packed_width',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Packed Width'),
          'description' => E::ts('Packed Width'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.packed_width',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Packed Width"),
          ],
          'add' => NULL,
        ],
        'inventory_product_variant_depth' => [
          'name' => 'packed_depth',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Packed Depth'),
          'description' => E::ts('Packed Depth'),
          'required' => FALSE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.packed_depth',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Packed Depth"),
          ],
          'add' => NULL,
        ],
        'inventory_product_variant_battery' => [
          'name' => 'product_variant_battery',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Battery'),
          'description' => E::ts('Battery backup time.'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_variant_battery',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_variant_speed' => [
          'name' => 'product_variant_speed',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Speed'),
          'description' => E::ts('Device Speed.'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.product_variant_speed',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_antenna' => [
          'name' => 'antenna',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Antenna'),
          'description' => E::ts('Supports external antenna'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.antenna',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_tether' => [
          'name' => 'tether',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Tether'),
          'description' => E::ts('Supports tethering via USB or Ethernet'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.tether',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_powerbank' => [
          'name' => 'powerbank',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Power Bank'),
          'description' => E::ts('Supports charging external devices'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.powerbank',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_batteryless' => [
          'name' => 'batteryless',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Battery Less'),
          'description' => E::ts('Can run without a battery'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.batteryless',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_network_4g' => [
          'name' => 'network_4g',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Network 4g'),
          'description' => E::ts('Supports 4G networks'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.network_4g',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_network_5g' => [
          'name' => 'network_5g',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Network 5g'),
          'description' => E::ts('Supports 5G networks'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.network_5g',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_has_sim' => [
          'name' => 'has_sim',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Has SIM'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.has_sim',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_has_device' => [
          'name' => 'has_device',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Has Device'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.has_device',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_warranty_type_id' => [
          'name' => 'warranty_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Warranty Type'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.warranty_type_id',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Warranty Type"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'warranty_type',
            'optionEditPath' => 'civicrm/admin/options/warranty_type',
          ],
          'add' => NULL,
        ],
        'inventory_product_variant_uom' => [
          'name' => 'uom',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Unit of Measure'),
          'description' => E::ts('Feet, pounds, and gallons are all examples of units of measure.'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.uom',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_screen' => [
          'name' => 'screen',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Screen'),
          'description' => E::ts('Screen size details. e.g. 5.81", OLED 2340x1080'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.screen',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_storage' => [
          'name' => 'storage',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Storage'),
          'description' => E::ts('Storage size. e.g. 128 GB'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.storage',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_memory' => [
          'name' => 'memory',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Memory'),
          'description' => E::ts('Product Memory size. e.g. 4 GB'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.memory',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_color' => [
          'name' => 'color',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Color'),
          'description' => E::ts('e.g. Black'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.color',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_premium_is_optional' => [
          'name' => 'premium_is_optional',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Premium: Is Optional'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.premium_is_optional',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_premium_needs_address' => [
          'name' => 'premium_needs_address',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Premium: Need Address'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.premium_needs_address',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_premium_shirt_count' => [
          'name' => 'premium_shirt_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Premium:Shirt Count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.premium_shirt_count',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'inventory_product_premium_device_count' => [
          'name' => 'premium_device_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Premium: Device Count'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.premium_device_count',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'warehouse_id' => [
          'name' => 'warehouse_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Warehouse ID'),
          'description' => E::ts('FK to Warehouse'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.warehouse_id',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventoryWarehouse',
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Warehouse"),
          ],
          'pseudoconstant' => [
            'table' => 'civicrm_inventory_warehouse',
            'keyColumn' => 'id',
            'labelColumn' => 'name',
          ],
          'add' => NULL,
        ],
        'inventory_product_quantity_available' => [
          'name' => 'quantity_available',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Quantity Available'),
          'description' => E::ts('The quantity on hand.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.quantity_available',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Quantity Available"),
          ],
          'add' => NULL,
        ],
        'inventory_product_minimum_quantity_stock_level' => [
          'name' => 'minimum_quantity_stock_level',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Minimum Stock Level'),
          'description' => E::ts('The minimum number of units required to ensure no shortages occur at this warehouse.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.minimum_quantity_stock_level',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Minimum Stock Level"),
          ],
          'add' => NULL,
        ],
        'inventory_product_maximum_quantity_stock_level' => [
          'name' => 'maximum_quantity_stock_level',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Maximum Stock Level'),
          'description' => E::ts('The maximum number of units desired in stock, i.e. to avoid overstocking.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.maximum_quantity_stock_level',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Maximum Stock Level"),
          ],
          'add' => NULL,
        ],
        'inventory_product_reorder_point' => [
          'name' => 'reorder_point',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ReOrder Point'),
          'description' => E::ts('The minimum number of units required to ensure no shortages occur at this warehouse.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.reorder_point',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("ReOrder Point"),
          ],
          'add' => NULL,
        ],
        'inventory_product_warehouse_row' => [
          'name' => 'row',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Row in Warehouse'),
          'description' => E::ts('Use to locate the item in warehouse'),
          'required' => FALSE,
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.row',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Row in Warehouse"),
          ],
          'add' => '5.63',
        ],
        'inventory_product_warehouse_shelf' => [
          'name' => 'shelf',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Warehouse shelf'),
          'description' => E::ts('Use to locate the item in warehouse'),
          'required' => FALSE,
          'maxlength' => 256,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.shelf',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Warehouse shelf"),
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'warehouse_shelf',
            'optionEditPath' => 'civicrm/admin/options/warehouse_shelf',
          ],
          'add' => '5.63',
        ],
        'weight' => [
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Order'),
          'description' => E::ts('Controls display sort order.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.weight',
          'default' => '1',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.75',
        ],
        'inventory_product_is_serialize' => [
          'name' => 'is_serialize',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Serialized'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.is_serialize',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_is_discontinued' => [
          'name' => 'is_discontinued',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Discontinued'),
          'description' => E::ts('When a model is discontinued, a membership cannot be renewed until they upgrade the device.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.is_discontinued',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Active'),
          'description' => E::ts('If not active, new devices of this type will not be available. Users with existing devices of this type will still see their devices listed.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.is_active',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_inventory_display' => [
          'name' => 'inventory_display',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Inventory Display'),
          'description' => E::ts('Show or hide this model on the admin dashboard.'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_product.inventory_display',
          'export' => TRUE,
          'default' => '1',
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_product_inventory_status_note' => [
          'name' => 'inventory_status_note',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Inventory note'),
          'description' => E::ts('If defined, this note will replace the default inventory message that is based on the inventory status.'),
          'required' => FALSE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.inventory_status_note',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.63',
        ],
        'inventory_product_inventory_status' => [
          'name' => 'inventory_status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Inventory Status'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_product.inventory_status',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_product',
          'entity' => 'InventoryProduct',
          'bao' => 'CRM_Inventory_DAO_InventoryProduct',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Inventory Status"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Inventory_Utils::productInventoryStatus',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'inventory_product', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'inventory_product', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
