<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.inventory/xml/schema/CRM/Inventory/InventoryShipmentLabels.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a6c25cc1c44da5d0345d3a3cd51664cb)
 */
use CRM_Inventory_ExtensionUtil as E;

/**
 * Database access object for the InventoryShipmentLabels entity.
 */
class CRM_Inventory_DAO_InventoryShipmentLabels extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_inventory_shipment_labels';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique InventoryShipmentLabels ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $updated_date;

  /**
   * FK to Sales
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sales_id;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_valid;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_paid;

  /**
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $has_error;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $provider;

  /**
   * Shipment Amount
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * @var string
   *   (SQL type: varchar(4))
   *   Note that values will be retrieved from the database as a string.
   */
  public $currency;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $resource_id;

  /**
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $tracking_id;

  /**
   * Shipment details.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $shipment;

  /**
   * Shipment Purchase details.
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $purchase;

  /**
   * FK to Contact
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_inventory_shipment_labels';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Inventory Shipment Labelses') : E::ts('Inventory Shipment Labels');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique InventoryShipmentLabels ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.id',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'inventory_shipment_label_created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Created Date'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.created_date',
          'headerPattern' => '/created(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'inventory_shipment_label_updated_date' => [
          'name' => 'updated_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Updated Date'),
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.updated_date',
          'headerPattern' => '/updated(.?date)?/i',
          'dataPattern' => '/^\d{4}-?\d{2}-?\d{2} ?(\d{2}:?\d{2}:?(\d{2})?)?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'sales_id' => [
          'name' => 'sales_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Sales ID'),
          'description' => E::ts('FK to Sales'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.sales_id',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventorySales',
          'add' => NULL,
        ],
        'inventory_shipment_label_is_valid' => [
          'name' => 'is_valid',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Valid?'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.is_valid',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_shipment_label__is_paid' => [
          'name' => 'is_paid',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Paid?'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.is_paid',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_shipment_label_has_error' => [
          'name' => 'has_error',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Has Error?'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.has_error',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'inventory_shipment_label_provider' => [
          'name' => 'provider',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Shipment Provider'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.provider',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'add' => '5.63',
        ],
        'inventory_shipment_label_amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Amount'),
          'description' => E::ts('Shipment Amount'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.amount',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Label Amount"),
          ],
          'add' => NULL,
        ],
        'inventory_shipment_label_currency' => [
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Currency'),
          'required' => FALSE,
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.currency',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'add' => '5.63',
        ],
        'inventory_shipment_label_resource_id' => [
          'name' => 'resource_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Resource ID'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.resource_id',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'add' => '5.63',
        ],
        'inventory_shipment_label_tracking_id' => [
          'name' => 'tracking_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Tracking ID'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.tracking_id',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'add' => '5.63',
        ],
        'inventory_shipment_label_shipment' => [
          'name' => 'shipment',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Shipment Details'),
          'description' => E::ts('Shipment details.'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.shipment',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'inventory_shipment_label_purchase' => [
          'name' => 'purchase',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Shipment Label Purchase'),
          'description' => E::ts('Shipment Purchase details.'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_shipment_labels.purchase',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => '5.63',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_shipment_labels.contact_id',
          'table_name' => 'civicrm_inventory_shipment_labels',
          'entity' => 'InventoryShipmentLabels',
          'bao' => 'CRM_Inventory_DAO_InventoryShipmentLabels',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'inventory_shipment_labels', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'inventory_shipment_labels', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
