<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.inventory/xml/schema/CRM/Inventory/InventorySalesDetail.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:1791b94b9cdab3ea349b0a26084a9252)
 */
use CRM_Inventory_ExtensionUtil as E;

/**
 * Database access object for the InventorySalesDetail entity.
 */
class CRM_Inventory_DAO_InventorySalesDetail extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_inventory_sales_detail';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Inventory Sales Detail ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Sales
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sales_id;

  /**
   * FK to Product Variant
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_variant_id;

  /**
   * The quantity sold.
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_quantity;

  /**
   * FK to Warehouse
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $warehouse_id;

  /**
   * e.g IMEI (International Mobile Equipment Identity) number .
   *
   * @var string
   *   (SQL type: varchar(100))
   *   Note that values will be retrieved from the database as a string.
   */
  public $product_unique_id;

  /**
   * Product Purchase price
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $purchase_price;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_inventory_sales_detail';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Inventory Sales Details') : E::ts('Inventory Sales Detail');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'sales_id', 'civicrm_inventory_sales', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'product_variant_id', 'civicrm_inventory_product_variant', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'warehouse_id', 'civicrm_inventory_warehouse', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Inventory Sales Detail ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_sales_detail.id',
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'sales_id' => [
          'name' => 'sales_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Sales ID'),
          'description' => E::ts('FK to Sales'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_sales_detail.sales_id',
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventorySales',
          'add' => NULL,
        ],
        'product_variant_id' => [
          'name' => 'product_variant_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Product Variant ID'),
          'description' => E::ts('FK to Product Variant'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_sales_detail.product_variant_id',
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventoryProductVariant',
          'add' => NULL,
        ],
        'inventory_salesdetail_quantity_available' => [
          'name' => 'product_quantity',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Product quantity'),
          'description' => E::ts('The quantity sold.'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_sales_detail.product_quantity',
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'add' => NULL,
        ],
        'warehouse_id' => [
          'name' => 'warehouse_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Warehouse ID'),
          'description' => E::ts('FK to Warehouse'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_inventory_sales_detail.warehouse_id',
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'FKClassName' => 'CRM_Inventory_DAO_InventoryWarehouse',
          'add' => NULL,
        ],
        'inventory_salesdetail_product_unique_id' => [
          'name' => 'product_unique_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Product Unique ID'),
          'description' => E::ts('e.g IMEI (International Mobile Equipment Identity) number .'),
          'required' => FALSE,
          'maxlength' => 100,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_sales_detail.product_unique_id',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'add' => '5.63',
        ],
        'inventory_salesdetail_purchase_price' => [
          'name' => 'purchase_price',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Purchase Price'),
          'description' => E::ts('Product Purchase price'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => TRUE,
            'export' => TRUE,
            'duplicate_matching' => TRUE,
            'token' => FALSE,
          ],
          'import' => TRUE,
          'where' => 'civicrm_inventory_sales_detail.purchase_price',
          'dataPattern' => '/^\d+(\.\d{2})?$/',
          'export' => TRUE,
          'table_name' => 'civicrm_inventory_sales_detail',
          'entity' => 'InventorySalesDetail',
          'bao' => 'CRM_Inventory_DAO_InventorySalesDetail',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Purchase Price"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'inventory_sales_detail', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'inventory_sales_detail', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
