<?php
return [
  'name' => 'InventoryProduct',
  'table' => 'civicrm_inventory_product',
  'class' => 'CRM_Inventory_DAO_InventoryProduct',
  'getInfo' => fn() => [
    'title' => ts('Inventory Product'),
    'title_plural' => ts('Inventory Products'),
    'description' => ts('Product table.'),
    'log' => TRUE,
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Number',
      'required' => TRUE,
      'description' => ts('Unique InventoryProduct ID'),
      'unique_name' => 'inventory_product_id',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'product_code' => [
      'title' => ts('Product Code'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => ts('Product Code SKU.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_code',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'external_code' => [
      'title' => ts('External Code'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_external_code',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_name' => [
      'title' => ts('Product Name'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'required' => TRUE,
      'add' => '5.63',
      'unique_name' => 'inventory_product_name',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_description' => [
      'title' => ts('Product Description'),
      'sql_type' => 'varchar(512)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_description',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 512,
      ],
    ],
    'product_brand' => [
      'title' => ts('Product Brand'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_brand',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_note' => [
      'title' => ts('Product Note'),
      'sql_type' => 'text',
      'input_type' => 'TextArea',
      'description' => ts('Product details.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_note',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'rows' => 4,
        'cols' => 60,
      ],
    ],
    'product_category_id' => [
      'title' => ts('Product Category'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'required' => TRUE,
      'description' => ts('FK to Category'),
      'unique_name' => 'inventory_product_category_id',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'entity_reference' => [
        'entity' => 'InventoryCategory',
        'key' => 'id',
        'on_delete' => 'RESTRICT',
      ],
    ],
    'is_disable' => [
      'title' => ts('Is Disable'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_is_disable',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'is_discontinued' => [
      'title' => ts('Is Discontinued'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_is_discontinued',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'image_actual' => [
      'title' => ts('Image'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('File url.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_image',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
  ],
];
