<?php
return [
  'name' => 'InventoryProductVariant',
  'table' => 'civicrm_inventory_product_variant',
  'class' => 'CRM_Inventory_DAO_InventoryProductVariant',
  'getInfo' => fn() => [
    'title' => ts('Inventory Product Variant'),
    'title_plural' => ts('Inventory Product Variants'),
    'description' => ts('Product Variant table'),
    'log' => TRUE,
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Number',
      'required' => TRUE,
      'description' => ts('Unique Inventory Product Variant ID'),
      'unique_name' => 'inventory_product_variant_id',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'product_id' => [
      'title' => ts('Product ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'description' => ts('FK to Product'),
      'entity_reference' => [
        'entity' => 'InventoryProduct',
        'key' => 'id',
        'on_delete' => 'CASCADE',
      ],
    ],
    'listed_price' => [
      'title' => ts('Listed Price'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => ts('Product listed price'),
      'unique_name' => 'inventory_product_variant_listed_price',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Listed Price'),
      ],
    ],
    'current_price' => [
      'title' => ts('Current Price'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => ts('Product Current price'),
      'unique_name' => 'inventory_product_variant_current_price',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Curent Price'),
      ],
    ],
    'product_variant_sku_code' => [
      'title' => ts('Product Variant SKU Code'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_sku_code',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_variant_phone_number' => [
      'title' => ts('Phone Number'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('Phone number linked with device.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_phone_number',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_variant_unique_id' => [
      'title' => ts('Product Variant Unique ID'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('e.g IMEI (International Mobile Equipment Identity) number .'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_unique_id',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_variant_details' => [
      'title' => ts('Product Variant Details'),
      'sql_type' => 'text',
      'input_type' => 'TextArea',
      'description' => ts('Product Variant details.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_details',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'rows' => 4,
        'cols' => 60,
      ],
    ],
    'is_disable' => [
      'title' => ts('Is Disable'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_variant_is_disable',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'is_discontinued' => [
      'title' => ts('Is Discontinued'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_variant_is_discontinued',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'packed_weight' => [
      'title' => ts('Packed Weight'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'description' => ts('Packed Weight'),
      'unique_name' => 'inventory_product_variant_weight',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Packed Weight'),
      ],
    ],
    'packed_height' => [
      'title' => ts('Packed Height'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'description' => ts('Packed Height'),
      'unique_name' => 'inventory_product_variant_height',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Packed Height'),
      ],
    ],
    'packed_width' => [
      'title' => ts('Packed Width'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'description' => ts('Packed Width'),
      'unique_name' => 'inventory_product_variant_width',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Packed Width'),
      ],
    ],
    'packed_depth' => [
      'title' => ts('Packed Depth'),
      'sql_type' => 'decimal(20,2)',
      'input_type' => 'Text',
      'description' => ts('Packed Depth'),
      'unique_name' => 'inventory_product_variant_depth',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Packed Depth'),
      ],
    ],
    'product_variant_battery' => [
      'title' => ts('Product Battery'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('Battery backup time.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_battery',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_variant_speed' => [
      'title' => ts('Product Speed'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('Device Speed.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_speed',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'antenna' => [
      'title' => ts('Antenna'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_antenna',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'tether' => [
      'title' => ts('Tether'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_tether',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'powerbank' => [
      'title' => ts('Power Bank'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_powerbank',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'batteryless' => [
      'title' => ts('Battery Less'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_batteryless',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'network_4g' => [
      'title' => ts('Network 4g'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_network_4g',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'network_5g' => [
      'title' => ts('Network 5g'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_network_5g',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'has_sim' => [
      'title' => ts('Has SIM'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_has_sim',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'has_device' => [
      'title' => ts('Has Device'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_has_device',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'warranty_type_id' => [
      'title' => ts('Warranty Type'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Number',
      'unique_name' => 'inventory_product_warranty_type_id',
      'usage' => ['export'],
    ],
    'image_thumbnail' => [
      'title' => ts('Thumbnail Image'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_thumbnail',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'image_actual' => [
      'title' => ts('Image'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_image',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'uom' => [
      'title' => ts('Unit of Measure'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'description' => ts('Feet, pounds, and gallons are all examples of units of measure.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_uom',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'product_variant_status' => [
      'title' => ts('Product Status'),
      'sql_type' => 'varchar(100)',
      'input_type' => 'Text',
      'add' => '5.63',
      'unique_name' => 'inventory_product_variant_status',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'maxlength' => 100,
      ],
    ],
    'replaced_product_id' => [
      'title' => ts('Replaced Product ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'description' => ts('Optional Product.'),
      'usage' => ['export'],
      'input_attrs' => [
        'label' => ts('Primary Product'),
      ],
      'entity_reference' => [
        'entity' => 'InventoryProductVariant',
        'key' => 'id',
        'on_delete' => 'SET NULL',
      ],
    ],
    'is_serialize' => [
      'title' => ts('Is Serialized'),
      'sql_type' => 'boolean',
      'input_type' => 'CheckBox',
      'unique_name' => 'inventory_product_is_serialize',
      'default' => FALSE,
      'usage' => ['export'],
    ],
    'membership_id' => [
      'title' => ts('Membership ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'description' => ts('Membership ID Associated with product.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_membership_id',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Membership ID'),
      ],
      'entity_reference' => [
        'entity' => 'Membership',
        'key' => 'id',
        'on_delete' => 'SET NULL',
      ],
    ],
    'warranty_start_date' => [
      'title' => ts('Warranty Start Date'),
      'sql_type' => 'datetime',
      'input_type' => 'Select Date',
      'unique_name' => 'inventory_product_warranty_start_date',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'format_type' => 'activityDateTime',
      ],
    ],
    'warranty_end_date' => [
      'title' => ts('Warranty End Date'),
      'sql_type' => 'datetime',
      'input_type' => 'Select Date',
      'unique_name' => 'inventory_product_warranty_end_date',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'format_type' => 'activityDateTime',
      ],
    ],
    'sales_id' => [
      'title' => ts('Sales ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'EntityRef',
      'description' => ts('Sales ID Associated with sales tables.'),
      'add' => '5.63',
      'unique_name' => 'inventory_product_sales_id',
      'usage' => [
        'import',
        'export',
        'duplicate_matching',
      ],
      'input_attrs' => [
        'label' => ts('Sales ID'),
      ],
      'entity_reference' => [
        'entity' => 'InventorySales',
        'key' => 'id',
        'on_delete' => 'SET NULL',
      ],
    ],
  ],
];
